using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8D67572CD7A434A
{
	// Script generated by Pega Robotics Studio 8.0.1089.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D67572CD7A434A")]
	public sealed class Script
	{
		public string Roundup(string value)
		{
			// Add your code here...
		double precise = Convert.ToDouble();
		int rounded = (int)Math.Round(precise,0);
		return rounded;
		}
	}
}
